# Generated by Django 3.1 on 2020-08-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(default='Netflix1', max_length=30)),
                ('product_name', models.CharField(max_length=30)),
                ('category', models.CharField(default='monthly', max_length=30)),
                ('price', models.IntegerField(default=200)),
                ('account', models.CharField(default='', max_length=30)),
                ('password', models.CharField(default='qwerty', max_length=20)),
            ],
        ),
    ]
