# Generated by Django 3.1 on 2020-08-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orders_orderupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='account',
        ),
        migrations.RemoveField(
            model_name='product',
            name='password',
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
