# Generated by Django 3.1 on 2020-08-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200820_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('order_id', models.IntegerField(default='')),
                ('product_name', models.CharField(default='', max_length=30)),
                ('product_email', models.CharField(default='', max_length=70)),
                ('password', models.CharField(default='', max_length=70)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Reset',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('order_id', models.IntegerField(default='')),
                ('product_name', models.CharField(default='', max_length=30)),
                ('product_email', models.CharField(default='', max_length=70)),
                ('password', models.CharField(default='', max_length=70)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
