# Generated by Django 3.1 on 2020-09-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200912_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reset',
            name='order_id',
            field=models.IntegerField(default='1111'),
        ),
    ]
